### PR TITLE
Raw Data Storage

### PR DESCRIPTION
**Pull request by patman15**
In order to e.g. supply JSON+LD schema with appropriate data automatically, I added a "raw" field to store the server response in JSON format.
I also changed the query for default values to HTTPS to not mix secure and non secure queries in case the module is embedded in HTTPS sites.

### CODE REVIEW

**Comment by gmclelland** [comment]
@patman15 - I noticed it doesn't update the new "raw" database column if you have pre-existing records.  Even resaving the pre-existing records doesn't populate the "raw" column.  It works great with new records though.

Maybe we should add a check to see if the "raw" column is empty.  If the "raw" column is empty, then perform a geocode request and store the result in the "raw" column?

**Comment by gmclelland** [comment]
I'm thinking we can perform the check right here? https://github.com/madebymats/FieldtypeLeafletMapMarker/blob/de51667cafcffdbb9c94b16ed02c6dc6a47ab58d/InputfieldLeafletMapMarker.module#L244

**Comment by gmclelland** [comment]
Also probably here https://github.com/madebymats/FieldtypeLeafletMapMarker/blob/de51667cafcffdbb9c94b16ed02c6dc6a47ab58d/InputfieldLeafletMapMarker.module#L214

**Comment by gmclelland** [comment]
Also probably here https://github.com/madebymats/FieldtypeLeafletMapMarker/blob/4c9b52a8c126158e49d799571857128975483dab/LeafletMapMarker.php#L74

**Comment by patman15** [comment]
@gmclelland you are right, I skipped that for my first quick implementation, but it is an excellent idea. I'll think about it over the weekend. Shouldn't be too difficult as you suggest. :-)

**Comment by patman15** [comment]
I thought about it again. Actually, the problem only occurs right after update. All exiting entries don't get a geocode address, until you enter them again. The problem is that there is an empty "raw" field and no "address changed" event. I would suggest to implement the fill up of the field during database upgrade.

**Comment by gmclelland** [comment]
Thanks for checking on it patman15.

> I would suggest to implement the fill up of the field during database upgrade.

What will happen if someone later edits a page and changes the address?  Will the raw data get updated as well?

On my site I have a small number of pages with locations, but I'm willing to try out any changes you make.

**Comment by patman15** [comment]
> What will happen if someone later edits a page and changes the address? Will the raw data get updated as well?

Updates should work fine. The code updates the raw field everytime a geo  code request ist issued.  This ist usually everytime the location is changed.  Issue exists only with fields that exist prior to this update.

> but I'm willing to try out any changes 

Thanks, I'll patch the upgrade procedure soon.

**Pull request merged**
