### PR TITLE
Change required to run the database update

### PR DESCRIPTION
**Pull request by gmclelland**
This should fix some of the errors I was getting as described by https://processwire.com/talk/topic/9745-module-leaflet-map/?do=findComment&comment=161109

### CODE REVIEW

**Comment by gmclelland** [comment]
Thank you

**Comment by madebymats** [comment]
Thanks for fixing it!

**Comment by gmclelland** [comment]
@madebymats - I forgot... You will need to increment the module's version number so that everyone gets the new change.  You might need to increment all the module's version numbers?

**Comment by gmclelland** [comment]
@madebymats - I saw that you created a new release on Github, but I think we are going to need to edit each module's file and change the module's version numbers so that the Processwire.com's module directory will show that an update is available?  I could be wrong on how this works?

Since this module contains several nested modules, I'm guessing we need to make all the version numbers the same?

Thanks for giving me rights to contribute.  I won't commit anything unless I see something obvious.  I'm still new to Processwire.  I've only created two sites so far with it, but I really like it.

**Pull request merged**
